name: New Problem Implementation
description: Add a new LeetCode problem to the repository
title: '0001 - Two Sum'
labels: ['problem', 'implementation']
body:
  - type: input
    id: problem_number
    attributes:
      label: Problem Number
      description: LeetCode problem number (4-digit format)
      placeholder: '0001'
    validations:
      required: true

  - type: input
    id: problem_title
    attributes:
      label: Problem Title
      description: LeetCode problem title
      placeholder: 'Two Sum'
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: List all constraints (use categories if applicable)
      placeholder: |
        Array:
        - 2 <= nums.length <= 10^4

        Values:
        - -10^9 <= nums[i] <= 10^9
        - -10^9 <= target <= 10^9

        Other:
        - Only one valid answer exists
    validations:
      required: true

  - type: checkboxes
    id: implementation_checklist
    attributes:
      label: Implementation Checklist
      description: Track implementation progress
      options:
        - label: Create directory structure (`src/problems/xxxx-problem-name/`)
        - label: Define CONSTRAINTS constants in test file
        - label: Write comprehensive test cases
        - label: Implement solution(s)
        - label: Add complexity analysis in comments
        - label: Format code (`npm run format`)
        - label: Run all checks (`npm run check`)
        - label: Verify all tests pass
