name: New Problem Implementation
description: Add a new LeetCode problem to the repository
title: '0001 - Two Sum'
labels: ['problem', 'implementation']
body:
  - type: input
    id: problem_number
    attributes:
      label: Problem Number
      description: LeetCode problem number (4-digit format)
      placeholder: '0001'
    validations:
      required: true

  - type: input
    id: problem_title
    attributes:
      label: Problem Title
      description: LeetCode problem title
      placeholder: 'Two Sum'
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: List all constraints (use categories if applicable)
      placeholder: |
        Array:
        - 2 <= nums.length <= 10^4

        Values:
        - -10^9 <= nums[i] <= 10^9
        - -10^9 <= target <= 10^9

        Other:
        - Only one valid answer exists
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Test Design Principles
        
        Apply these common testing principles when implementing tests:
        
        1. Define CONSTRAINTS as constants (UPPER_SNAKE_CASE) at test file top
        2. Calculate derived values as variables (lowerCamelCase) within tests
        3. Consider worst-case scenarios (Identify O(n²) or exponential cases that stress the algorithm)
        4. Test with actual constraint boundaries, not just "large" values
        5. Handle numerical precision for floating-point problems
        6. Optimize test combinations (avoid redundant tests)
        7. Never optimize for specific test inputs - optimize for algorithmic efficiency

  - type: checkboxes
    id: implementation_checklist
    attributes:
      label: Implementation Checklist
      description: Track implementation progress
      options:
        - label: Create directory structure (`src/problems/xxxx-problem-name/`)
        - label: Define CONSTRAINTS constants in test file
        - label: Write comprehensive test cases
        - label: Implement solution(s)
        - label: Add complexity analysis in comments
        - label: Format code (`npm run format`)
        - label: Run lint checks (`npm run lint`)
        - label: Verify all tests pass
